# Generated by Django 3.0.14 on 2021-06-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя продавца', max_length=50, verbose_name='Имя продавца')),
                ('last_name', models.CharField(help_text='Введите фамилию продавца', max_length=50, verbose_name='Фамилия продавца')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название товара', max_length=200, verbose_name='Наименование товара')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение товара')),
                ('description', models.TextField(blank=True, help_text='Введите описание товара', verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('date_of_sale', models.DateTimeField(auto_now=True, verbose_name='Дата продажи')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая стоимость')),
                ('employee', models.ManyToManyField(to='mainapp.Employee', verbose_name='Продавец')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Item', verbose_name='Наименование товара')),
            ],
        ),
    ]
